<?php

namespace DoctrineProxies\__CG__\Omeka\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vocabulary extends \Omeka\Entity\Vocabulary implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'comment' => [parent::class, 'comment', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'label' => [parent::class, 'label', null, 8],
        "\0".'*'."\0".'namespaceUri' => [parent::class, 'namespaceUri', null, 8],
        "\0".'*'."\0".'owner' => [parent::class, 'owner', null, 8],
        "\0".'*'."\0".'prefix' => [parent::class, 'prefix', null, 8],
        "\0".'*'."\0".'properties' => [parent::class, 'properties', null, 8],
        "\0".'*'."\0".'resourceClasses' => [parent::class, 'resourceClasses', null, 8],
        'comment' => [parent::class, 'comment', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'label' => [parent::class, 'label', null, 8],
        'namespaceUri' => [parent::class, 'namespaceUri', null, 8],
        'owner' => [parent::class, 'owner', null, 8],
        'prefix' => [parent::class, 'prefix', null, 8],
        'properties' => [parent::class, 'properties', null, 8],
        'resourceClasses' => [parent::class, 'resourceClasses', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
