# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.supported_locales:
        - en
        - fr
        - es
    app.tenant_base_domain: '%env(APP_TENANT_BASE_DOMAIN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Omeka\Db\Event\Subscriber\Schema:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchemaTable }

    App\Menu\SiteMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createSiteMenu, alias: site_admin }

    App\Menu\AdminMenuBuilder:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: knp_menu.menu_builder, method: createAdminSiteMenu, alias: admin_site }
            - { name: knp_menu.menu_builder, method: createAdminResourceMenu, alias: admin_resource }
            - { name: knp_menu.menu_builder, method: createAdminGlobalMenu, alias: admin_global }
            - { name: knp_menu.menu_builder, method: createAdminModuleMenu, alias: admin_module }

    App\Service\LegacyOmekaApplication:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\LegacyViewRenderer: ~

    App\Service\OmekaAdminFormService: ~

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
